// <auto-generated />
using DBTraining;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DBTraining.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220523152341_ActiveCompanies")]
    partial class ActiveCompanies
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("DBTraining.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("company_id");

                    b.Property<int>("Employees")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Enterprises", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Employees = 0,
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = 2,
                            Employees = 0,
                            Name = "Google"
                        },
                        new
                        {
                            Id = 3,
                            Employees = 0,
                            Name = "Amazon"
                        });
                });

            modelBuilder.Entity("DBTraining.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("country_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("DBTraining.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("FullAges")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HaveJob")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasCheckConstraint("FullAges", "FullAges > 0 AND FullAges < 120");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Genry",
                            FullAges = 18,
                            HaveJob = false,
                            LastName = "Gustav"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Bob",
                            FullAges = 37,
                            HaveJob = false,
                            LastName = "Vatson"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Nick",
                            FullAges = 25,
                            HaveJob = false,
                            LastName = "Nelson"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
